version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - 3307:3307
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - ./mysql_data:/var/lib/mysql

  api:
    build: ./api
    environment:
      - APP_ENV=development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/app
      - bundle_data:/usr/local/bundle
    ports:
      - 3004:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

  web:
    image: node:18
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    user: root
    working_dir: /nuxt
    volumes:
      - ./web:/nuxt
      - /nuxt/node_modules
    command:
      - bash
      - -c
      - |
        yarn install
        yarn dev -p 3003
    ports:
      - '3003:3003'
volumes:
  mysql_data:
  bundle_data:
