version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - 3307:3307
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - ./mysql_data:/var/lib/mysql

  api:
    build: ./api
    environment:
      - APP_ENV=development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3004 -b '0.0.0.0'"
    volumes:
      - ./api:/app
      - bundle_data:/usr/local/bundle
    ports:
      - 3004:3004
    depends_on:
      - db
    tty: true
    stdin_open: true

  web:
    image: node:18
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    user: root
    working_dir: /nuxt
    volumes:
      - ./web:/nuxt
      - /nuxt/node_modules
    command:
      - bash
      - -c
      - |
        yarn install
        yarn dev -p 3003
    ports:
      - '3003:3003'
      - '24678:24678'
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - '8001:8080'
    volumes:
      - ./docs/openapi.yaml:/tmp/openapi.yaml
    environment:
      SWAGGER_FILE: /tmp/openapi.yaml

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - '8002:8080'
    volumes:
      - ./docs/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      API_URL: openapi.yaml

volumes:
  mysql_data:
  bundle_data:
