version: "3"

services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - ./mysql_data:/var/lib/mysql
    
  backend:
    build: ./backend
    environment:
      - APP_ENV=development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
      - bundle_data:/usr/local/bundle
    ports:
      - 3001:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    
  frontend:
    image: node:18
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    user: root
    working_dir: /nuxt
    volumes:
      - ./frontend:/nuxt
      - /nuxt/node_modules
    command: 
      - bash
      - -c
      - |
        yarn install
        yarn dev -p 3000
    ports:
      - "3000:3000"
volumes:
  mysql_data:
  bundle_data:
